# Generated by Django 4.1.5 on 2023-02-13 07:14

import api.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name|Имя')),
                ('surname', models.CharField(max_length=128, verbose_name='Surname|Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Phone Number|Номер телефона')),
                ('profile_pic', models.ImageField(upload_to=api.models.user_directory_path, verbose_name='Profile Picture|Аватарка')),
                ('on_campus', models.BooleanField(default=False, verbose_name='On Campus|На Кампусе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At|Создано')),
                ('role', models.CharField(max_length=128, verbose_name='Role|Роль')),
                ('gmail', models.EmailField(max_length=128, verbose_name='Gmail|Почта')),
                ('gender', models.IntegerField(choices=[(0, 'Male|Мужской'), (1, 'Female|Женский')], verbose_name='Gender|Пол')),
            ],
            options={
                'verbose_name': 'Person|Человек',
                'verbose_name_plural': 'People|Люди',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_entry', models.DateTimeField(auto_now_add=True, verbose_name='Datetime Entry|Время входа')),
                ('datetime_exit', models.DateTimeField(blank=True, null=True, verbose_name='Datetime Exit|Время выхода')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.person', verbose_name='Person|Человек')),
            ],
            options={
                'verbose_name': 'Record|Запись',
                'verbose_name_plural': 'Records|Записи',
            },
        ),
    ]
