# Generated by Django 4.1.6 on 2023-02-15 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='gmail',
            new_name='email',
        ),
    ]
