# Generated by Django 4.1.6 on 2023-03-05 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_person_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(upload_to='uploads/profile_pictures/', verbose_name='Profile Picture|Аватарка'),
        ),
        migrations.CreateModel(
            name='AWSImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/AWSImages', verbose_name='Images|Фотография')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.person', verbose_name='Person|Человек')),
            ],
        ),
    ]
