# Generated by Django 4.1.5 on 2023-02-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_person_record_delete_attendance_delete_student"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "verbose_name": "Person|Человек",
                "verbose_name_plural": "People|Люди",
            },
        ),
        migrations.AlterModelOptions(
            name="record",
            options={
                "verbose_name": "Record|Запись",
                "verbose_name_plural": "Records|Записи",
            },
        ),
    ]
