# Generated by Django 4.1.6 on 2023-03-07 17:06

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_alter_person_profile_pic_awsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awsimage',
            name='image',
            field=models.ImageField(upload_to=api.models.awsimagedir, verbose_name='Images|Фотография'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
