# Generated by Django 4.1.6 on 2023-03-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_awsimage_image_alter_person_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='major',
            field=models.IntegerField(choices=[(0, 'CS'), (1, 'CM')], null=True, verbose_name='Major|Факультет'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_pic',
            field=models.ImageField(upload_to='static/uploads/profile_pictures/', verbose_name='Profile Picture|Аватарка'),
        ),
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.IntegerField(choices=[(0, 'Student'), (2023, 'Student-2023'), (2024, 'Student-2024'), (2025, 'Student-2025'), (2026, 'Student-2026'), (2027, 'Student-2027'), (2028, 'Student-2028'), (2029, 'Student-2029'), (2030, 'Student-2030'), (2031, 'Student-2031'), (2032, 'Student-2032'), (2033, 'Student-2033'), (2034, 'Student-2034'), (2035, 'Student-2035')], default=0, verbose_name='Role|Роль'),
        ),
    ]
